// Auto-generated from Mtb151.AsmDatasetOverviewTable.SD1.tsv (Mtb Set ID
// column dropped) joined against the report file list by SampleID.
const SAMPLES = [
  {
    "sample": "01_R1134",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234900",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234892",
    "primaryLineage": "lineage4",
    "lineage": "lineage4",
    "file": "reports/01_R1134.html"
  },
  {
    "sample": "01_R1430",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234890",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234906",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1",
    "file": "reports/01_R1430.html"
  },
  {
    "sample": "02_R0894",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234891",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234881",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/02_R0894.html"
  },
  {
    "sample": "02_R1179",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234897",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234904",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/02_R1179.html"
  },
  {
    "sample": "02_R1708",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234893",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234882",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/02_R1708.html"
  },
  {
    "sample": "02_R1896",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234894",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234883",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/02_R1896.html"
  },
  {
    "sample": "18_0621851",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030323",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR4816407",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/18_0621851.html"
  },
  {
    "sample": "3003-06",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196858",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196859",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/3003-06.html"
  },
  {
    "sample": "4549-04",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196852",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196853",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/4549-04.html"
  },
  {
    "sample": "696-05",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196845",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196846",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/696-05.html"
  },
  {
    "sample": "702-06",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196843",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196844",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/702-06.html"
  },
  {
    "sample": "706-05",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196841",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196842",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/706-05.html"
  },
  {
    "sample": "8129-04",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196840",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196851",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/8129-04.html"
  },
  {
    "sample": "8651-04",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196860",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196861",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/8651-04.html"
  },
  {
    "sample": "9050-05",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196816",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196817",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/9050-05.html"
  },
  {
    "sample": "M0003941_3",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234896",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234902",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/M0003941_3.html"
  },
  {
    "sample": "M0010874_7",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234889",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234905",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/M0010874_7.html"
  },
  {
    "sample": "M0011368_9",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234886",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234898",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1",
    "file": "reports/M0011368_9.html"
  },
  {
    "sample": "M0014888_3",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234887",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234899",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/M0014888_3.html"
  },
  {
    "sample": "M0016395_7",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234888",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234901",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.2",
    "file": "reports/M0016395_7.html"
  },
  {
    "sample": "M0016737_0",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234895",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234884",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.5",
    "file": "reports/M0016737_0.html"
  },
  {
    "sample": "M0017522_5",
    "datasetTag": "Farhat_Peru_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR17234903",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR17234885",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1",
    "file": "reports/M0017522_5.html"
  },
  {
    "sample": "MT_0080",
    "datasetTag": "Lee_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR9588640",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR9588558",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2",
    "file": "reports/MT_0080.html"
  },
  {
    "sample": "N0004",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964408,ERR964415",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704697",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/N0004.html"
  },
  {
    "sample": "N0054",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964410,ERR964417",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704678",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/N0054.html"
  },
  {
    "sample": "N0072",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964402,ERR956956",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704680",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/N0072.html"
  },
  {
    "sample": "N0091",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964422,ERR968288",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704681",
    "primaryLineage": "lineage6",
    "lineage": "lineage6",
    "file": "reports/N0091.html"
  },
  {
    "sample": "N0145",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR956958,ERR964404",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704702",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/N0145.html"
  },
  {
    "sample": "N0153",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR956957,ERR964403",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR3183990",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.1.1",
    "file": "reports/N0153.html"
  },
  {
    "sample": "N0155",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964407,ERR964414",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704684",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/N0155.html"
  },
  {
    "sample": "N1176",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR1036243,ERR1025289,ERR1036244",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704686",
    "primaryLineage": "lineage5",
    "lineage": "lineage5",
    "file": "reports/N1176.html"
  },
  {
    "sample": "N1177",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR987691,ERR999930",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR3183991",
    "primaryLineage": "lineage6",
    "lineage": "lineage6",
    "file": "reports/N1177.html"
  },
  {
    "sample": "N1202",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR968284,ERR968289",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704688",
    "primaryLineage": "lineage6",
    "lineage": "lineage6",
    "file": "reports/N1202.html"
  },
  {
    "sample": "N1272",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964421,ERR968287",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704692",
    "primaryLineage": "lineage5",
    "lineage": "lineage5",
    "file": "reports/N1272.html"
  },
  {
    "sample": "N1274",
    "datasetTag": "ChinerOms_2019",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "ERR964409,ERR964416",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR2704693",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/N1274.html"
  },
  {
    "sample": "QC-1",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196838",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196839",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/QC-1.html"
  },
  {
    "sample": "QC-10",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196819",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196820",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/QC-10.html"
  },
  {
    "sample": "QC-3",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196834",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196835",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/QC-3.html"
  },
  {
    "sample": "QC-4",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196832",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196833",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/QC-4.html"
  },
  {
    "sample": "QC-5",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196830",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196831",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/QC-5.html"
  },
  {
    "sample": "QC-6",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196827",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196828",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/QC-6.html"
  },
  {
    "sample": "QC-7",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196825",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196826",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3",
    "file": "reports/QC-7.html"
  },
  {
    "sample": "QC-8",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196823",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196824",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/QC-8.html"
  },
  {
    "sample": "QC-9",
    "datasetTag": "Peker2021",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "SRR14196821",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR14196822",
    "primaryLineage": "lineage3",
    "lineage": "lineage3",
    "file": "reports/QC-9.html"
  },
  {
    "sample": "R15311",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030471",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030447",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.2.1",
    "file": "reports/R15311.html"
  },
  {
    "sample": "R18040",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030467",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030359",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R18040.html"
  },
  {
    "sample": "R18043",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030394",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030388",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R18043.html"
  },
  {
    "sample": "R20260",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030283",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030270",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R20260.html"
  },
  {
    "sample": "R20574",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030530",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987402",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R20574.html"
  },
  {
    "sample": "R20896",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030378",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362771",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/R20896.html"
  },
  {
    "sample": "R21363",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030360",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987445",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/R21363.html"
  },
  {
    "sample": "R21408",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030440",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987267",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R21408.html"
  },
  {
    "sample": "R21770",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030350",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6052025",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/R21770.html"
  },
  {
    "sample": "R21839",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030533",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6052043",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/R21839.html"
  },
  {
    "sample": "R21893",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030424",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362661",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R21893.html"
  },
  {
    "sample": "R22601",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030280",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030306",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R22601.html"
  },
  {
    "sample": "R23146",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030462",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030461",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R23146.html"
  },
  {
    "sample": "R23571",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030465",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362166",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/R23571.html"
  },
  {
    "sample": "R23887",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030485",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9119979",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.2.2",
    "file": "reports/R23887.html"
  },
  {
    "sample": "R24100",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030468",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030405",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/R24100.html"
  },
  {
    "sample": "R24120",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030248",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987430",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R24120.html"
  },
  {
    "sample": "R25048",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030431",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030407",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R25048.html"
  },
  {
    "sample": "R26778",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030415",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030524",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R26778.html"
  },
  {
    "sample": "R26791",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030414",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362506",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R26791.html"
  },
  {
    "sample": "R27252",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030426",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9120067",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.2.2",
    "file": "reports/R27252.html"
  },
  {
    "sample": "R27657",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030354",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030275",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R27657.html"
  },
  {
    "sample": "R27725",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030509",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030459",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R27725.html"
  },
  {
    "sample": "R27937",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030489",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362282",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R27937.html"
  },
  {
    "sample": "R28012",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030498",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030482",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R28012.html"
  },
  {
    "sample": "R28581",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030321",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987281",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/R28581.html"
  },
  {
    "sample": "R28703",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030343",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987444",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R28703.html"
  },
  {
    "sample": "R28980",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030277",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362131",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R28980.html"
  },
  {
    "sample": "R29598",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030520",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987292",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/R29598.html"
  },
  {
    "sample": "R29816",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030346",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR6362582",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R29816.html"
  },
  {
    "sample": "R30078",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030386",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030317",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R30078.html"
  },
  {
    "sample": "R30215",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030506",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9120135",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R30215.html"
  },
  {
    "sample": "R30234",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030336",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030526",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R30234.html"
  },
  {
    "sample": "R30396",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030408",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987307",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/R30396.html"
  },
  {
    "sample": "R30420",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030287",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR5987210",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R30420.html"
  },
  {
    "sample": "R31095",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030488",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030358",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R31095.html"
  },
  {
    "sample": "R32929",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030253",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030331",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.2",
    "file": "reports/R32929.html"
  },
  {
    "sample": "R36431",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030327",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030393",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R36431.html"
  },
  {
    "sample": "R37765",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030454",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030318",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/R37765.html"
  },
  {
    "sample": "RW-TB008",
    "datasetTag": "Ngabonziza_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio RSII Subreads",
    "lrRunAccession": "SRR10828834",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR10828835",
    "primaryLineage": "lineage8",
    "lineage": "lineage8",
    "file": "reports/RW-TB008.html"
  },
  {
    "sample": "S0070-08",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267298",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267299",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/S0070-08.html"
  },
  {
    "sample": "S0085-01",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267290",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267291",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/S0085-01.html"
  },
  {
    "sample": "S0089-01",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267288",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267289",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/S0089-01.html"
  },
  {
    "sample": "S0106-01",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267286",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267287",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/S0106-01.html"
  },
  {
    "sample": "S0107-01",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267284",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267285",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/S0107-01.html"
  },
  {
    "sample": "S0123-01",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267296",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267297",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/S0123-01.html"
  },
  {
    "sample": "S0256-08",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267294",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267295",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/S0256-08.html"
  },
  {
    "sample": "S0262-02",
    "datasetTag": "TRUST_PB_Set1",
    "assemblyApproach": "PBccs_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II CCS (HiFi) Reads",
    "lrRunAccession": "SRR39267292",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR39267293",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/S0262-02.html"
  },
  {
    "sample": "TB1236",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761175",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6356988",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB1236.html"
  },
  {
    "sample": "TB1612",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761177",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6356966",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB1612.html"
  },
  {
    "sample": "TB2512",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761239",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516391",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB2512.html"
  },
  {
    "sample": "TB2659",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761178",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6356982",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB2659.html"
  },
  {
    "sample": "TB2661",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231461",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6356981",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/TB2661.html"
  },
  {
    "sample": "TB2780",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761176",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6356958",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB2780.html"
  },
  {
    "sample": "TB2968",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231609",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516420",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/TB2968.html"
  },
  {
    "sample": "TB2981",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761237",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516422",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB2981.html"
  },
  {
    "sample": "TB2995",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231612",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516404",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB2995.html"
  },
  {
    "sample": "TB3054",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761236",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516348",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.6.2",
    "file": "reports/TB3054.html"
  },
  {
    "sample": "TB3091",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761235",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516312",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB3091.html"
  },
  {
    "sample": "TB3113",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761238",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516302",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB3113.html"
  },
  {
    "sample": "TB3162",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39761234",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516410",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/TB3162.html"
  },
  {
    "sample": "TB3169",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231608",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR7516407",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/TB3169.html"
  },
  {
    "sample": "TB3237",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231411",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807727",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/TB3237.html"
  },
  {
    "sample": "TB3251",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231412",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807694",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.2.1",
    "file": "reports/TB3251.html"
  },
  {
    "sample": "TB3334",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231410",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807728",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2",
    "file": "reports/TB3334.html"
  },
  {
    "sample": "TB3368",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231415",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807705",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB3368.html"
  },
  {
    "sample": "TB3386",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231409",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807754",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.3.3",
    "file": "reports/TB3386.html"
  },
  {
    "sample": "TB3396",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR17231414",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR6807763",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/TB3396.html"
  },
  {
    "sample": "TB4620",
    "datasetTag": "TBPortals_2020",
    "assemblyApproach": "PBclr_LR_Flye_I3_SR_Pilon",
    "longReadTech": "PacBio Sequel II Subreads",
    "lrRunAccession": "SRR39760729",
    "shortReadTech": "Illumina",
    "srRunAccession": "SRR10303312",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.5",
    "file": "reports/TB4620.html"
  },
  {
    "sample": "mada_1-1",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030328",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030363",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-1.html"
  },
  {
    "sample": "mada_1-10",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030475",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030491",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-10.html"
  },
  {
    "sample": "mada_1-11",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030429",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030256",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1.1",
    "file": "reports/mada_1-11.html"
  },
  {
    "sample": "mada_1-12",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030376",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030288",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_1-12.html"
  },
  {
    "sample": "mada_1-15",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030412",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030263",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_1-15.html"
  },
  {
    "sample": "mada_1-30",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030400",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030473",
    "primaryLineage": "lineage3",
    "lineage": "lineage3.1.1",
    "file": "reports/mada_1-30.html"
  },
  {
    "sample": "mada_1-32",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030397",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030274",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.1.3",
    "file": "reports/mada_1-32.html"
  },
  {
    "sample": "mada_1-36",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030265",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030442",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-36.html"
  },
  {
    "sample": "mada_1-38",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030523",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030387",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.9",
    "file": "reports/mada_1-38.html"
  },
  {
    "sample": "mada_1-39",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030362",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030295",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-39.html"
  },
  {
    "sample": "mada_1-41",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030427",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030305",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1",
    "file": "reports/mada_1-41.html"
  },
  {
    "sample": "mada_1-44",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030304",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030519",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-44.html"
  },
  {
    "sample": "mada_1-50",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030418",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030353",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_1-50.html"
  },
  {
    "sample": "mada_1-51",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030355",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030463",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_1-51.html"
  },
  {
    "sample": "mada_1-53",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030511",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030450",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_1-53.html"
  },
  {
    "sample": "mada_102",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030515",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030301",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2",
    "file": "reports/mada_102.html"
  },
  {
    "sample": "mada_103",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030477",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030487",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/mada_103.html"
  },
  {
    "sample": "mada_105",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030345",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030446",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/mada_105.html"
  },
  {
    "sample": "mada_107",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030255",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030411",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_107.html"
  },
  {
    "sample": "mada_112",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030382",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030502",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/mada_112.html"
  },
  {
    "sample": "mada_115",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030452",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030269",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/mada_115.html"
  },
  {
    "sample": "mada_117",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030420",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030297",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_117.html"
  },
  {
    "sample": "mada_118",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030254",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030451",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_118.html"
  },
  {
    "sample": "mada_120",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030527",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030445",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.6.2.2",
    "file": "reports/mada_120.html"
  },
  {
    "sample": "mada_122",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030449",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030401",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_122.html"
  },
  {
    "sample": "mada_123",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030249",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030535",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_123.html"
  },
  {
    "sample": "mada_124",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030540",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030399",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/mada_124.html"
  },
  {
    "sample": "mada_126",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030448",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030396",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.6.2.2",
    "file": "reports/mada_126.html"
  },
  {
    "sample": "mada_128",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030507",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030504",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_128.html"
  },
  {
    "sample": "mada_129",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030419",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030289",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/mada_129.html"
  },
  {
    "sample": "mada_139",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030333",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030347",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/mada_139.html"
  },
  {
    "sample": "mada_151",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030341",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030458",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1.2.1",
    "file": "reports/mada_151.html"
  },
  {
    "sample": "mada_2-1",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030299",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030338",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_2-1.html"
  },
  {
    "sample": "mada_2-25",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030325",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030483",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.4.1.1",
    "file": "reports/mada_2-25.html"
  },
  {
    "sample": "mada_2-31",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030329",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030410",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.1",
    "file": "reports/mada_2-31.html"
  },
  {
    "sample": "mada_2-42",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030379",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030298",
    "primaryLineage": "lineage2",
    "lineage": "lineage2.2.1",
    "file": "reports/mada_2-42.html"
  },
  {
    "sample": "mada_2-46",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030349",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030308",
    "primaryLineage": "lineage1",
    "lineage": "lineage1.1.2",
    "file": "reports/mada_2-46.html"
  },
  {
    "sample": "mada_2-53",
    "datasetTag": "Hall2022",
    "assemblyApproach": "ONT_LR_FlyeI3M_SR_Pilon_PolyPolish",
    "longReadTech": "ONT R9.4.1 Reads",
    "lrRunAccession": "ERR9030466",
    "shortReadTech": "Illumina",
    "srRunAccession": "ERR9030413",
    "primaryLineage": "lineage4",
    "lineage": "lineage4.8",
    "file": "reports/mada_2-53.html"
  }
];
